# Generated by Django 4.1.4 on 2023-04-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_num',
            field=models.CharField(default='last order', max_length=255),
        ),
    ]
