# Generated by Django 4.1.4 on 2023-01-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Empty', max_length=255),
        ),
    ]
