# Generated by Django 4.1.4 on 2023-02-13 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_from', to='authuser.profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_to', to='authuser.profile'),
        ),
    ]
