# Generated by Django 4.1.4 on 2023-02-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0008_message_from_profile_alter_message_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_profile',
        ),
    ]
